version: '3.8'
services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "2855:2855"
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    networks:
      - app-network

  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    ports:
      - "7676:7676"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
